version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTNODEMAILER_PASSWORD=${NEXTNODEMAILER_PASSWORD}
      - NEXTNODEMAILER_USER=${NEXTNODEMAILER_USER}
      - EDGE_STORE_ACCESS_KEY=${EDGE_STORE_ACCESS_KEY}
      - EDGE_STORE_SECRET_KEY=${EDGE_STORE_SECRET_KEY}
      - NEXTAUTH_URL_PUBLIC_URL=${NEXTAUTH_URL_PUBLIC_URL}
    command: npm run dev